---
- name: Instalar paquetes haproxy
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ haproxy_pkg }}"

- name: Iniciar servicio haproxy
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ haproxy_srv }}"

- name: Configurar haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - reiniciar_haproxy
