---
- name: Instalar paquetes apache
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ apache_pkg }}"

- name: Iniciar servicio apache
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ apache_pkg }}"
