---
- name: Instalar paquetes postgres
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ postgres_pkg }}"

- name: Inicializar postgres
  command: postgresql-setup initdb

- name: Iniciar servicio postgres 
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ postgres_srv }}"
